### ISSUE TITLE
Thank your this amazing work

### ISSUE THREAD

**Issue by ElCapor** [Toxocious/Aetherim#6]
Hello sir , i don't currently have any bug with this software. I checked your blog and you are doing an awesome work. I got recently started in reverse engineering il2cpp. Your work is incredibly useful and well explained. Thank you very much for this work.
By the way do you have any discord server where it would be possible to talk about this project and maybe for example giving suggestions , improving this tool and helping each other by providing explanations ?

**Comment by Toxocious** [comment]
Hey!

Thanks for the positive words, I appreciate it! I'm glad that this project has helped you out.

I do have a Discord server that you can join if you would like to talk about this project or give suggestions, or something, which you can join by using this invite link: https://discord.gg/Km6btPhs

**Comment by ElCapor** [comment]
Thank you for your reply , however it appears that the link doesn't work anymore : (
You probably have to make a new one that doesn't expire and perhaps link it in the Readme.

**Comment by Toxocious** [comment]
Yep yep; thanks for bringing that to my attention.
I've updated the link to never expire, haha.

**Comment by Toxocious** [comment]
Closing as the discussion has moved to Discord.
