### ISSUE TITLE
Linux/macOS support?

### ISSUE THREAD

**Issue by BlueFalconHD** [Toxocious/Aetherim#9]
## Is your feature request related to a problem? Please describe.
Really struggling to mod a macOS game

## Describe the solution you'd like
Linux and macOS support

## Describe alternatives you've considered
Wine/virtualization

**Comment by Toxocious** [comment]
I do intend to add support for non-Windows based systems when I have the time.

**Comment by Toxocious** [comment]
Pretty late on this, but I've published a [new branch](https://github.com/Toxocious/Aetherim/tree/nix-support) that adds support for compiling on Linux (.so) and MacOS (.dylib).

The README has been updated to reflect changes made so far, and I intend to add very basic usage examples for Linux and MacOS over the weekend if I have the time.

**Comment by mogui** [comment]
can you point out a simple example for mac os I will be your tester !

**Comment by Toxocious** [comment]
> can you point out a simple example for mac os I will be your tester !

You could remove the first and last line in the current Windows example ([here](https://github.com/Toxocious/Aetherim/blob/nix-support/examples/windows.cpp)) and it should work for MacOS/Linux.

I haven't had the time to improve the example for Windows and translate the example to MacOS/Linux yet. If that's something you're interested in, do feel free to give it a try and make a pull request.

**Comment by Toxocious** [comment]
Closing as finished with commit [0410bf4](https://github.com/Toxocious/Aetherim/commit/0410bf42b83d8d60436794baadd5c43cda164337).
